version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        environment:
          TERM: xterm-256color
      - image: circleci/postgres:9.6.2
    working_directory: ~/Blogger
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            pip3 install virtualenv
            virtualenv -p python3 venv
            . venv/bin/activate
            pip3 install django
            pip install -r requirements.txt
            python manage.py test
