version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-python-django
    steps:
      - checkout
      - run:
          command: |
            pip3 install virtualenv
            virtualenv -p python3 venv
            . venv/bin/activate
            pip3 install django
            pip install -r requirements.txt
            python manage.py test
