version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        environment:
          TERM: xterm-256color
      - image: circleci/postgres:9.6.2
    working_directory: ~/code
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Run flake8 linter"
          command: docker-compose run web flake8
      - run:
          name: "Run tests"
          command: 
            cd ..
            docker-compose run web python manage.py test